name = "marketing_worker"
main = "src/index.ts"
compatibility_date = "2023-04-29"
d1_databases = [
	{ binding = "HVEC_MARKETING_DB", database_name = "genprose", database_id = "77147c1b-df67-4a72-9de7-7a4e90dd7e49", preview_database_id = "77147c1b-df67-4a72-9de7-7a4e90dd7e49" }
]

[dev]
port = 6002


[env.production]
d1_databases = [
	{ binding = "HVEC_MARKETING_DB", database_name = "genprose", database_id = "77147c1b-df67-4a72-9de7-7a4e90dd7e49" }
]