const PROGRESSIVE_STATUS = {
	QUEUED: "QUEUED",
	INPROGRESS: "INPROGRESS",
	COMPLETED: "COMPLETED",
	ERROR: "ERROR"
};

const CONTENT_TYPES = {
	EXTRACT_AUDIO: "EXTRACT_AUDIO",
	EXTRACT_KEYWORDS: "EXTRACT_KEYWORDS",
	EXTRACT_CONTENT: "EXTRACT_CONTENT",
	EXTRACT_TRANSCRIPT: "EXTRACT_TRANSCRIPT"
};

module.exports = {
	PROGRESSIVE_STATUS,
	CONTENT_TYPES
};