export const SEO = {
    home: {
        title: "Gen Prose | Auxiliary Content",
        description: "With Gen Prose, you can effortlessly transform relevant YouTube videos, podcasts, webinars, internal meetings, Zoom recordings, and more into engaging written content.",
        keywords: "genprose auxiliary content, free audio to text converter, podcast to text, ai seo content generator, genprose, seo blog articles, youtube video to text generator, audio to text converter, content writing services, generative ai in seconds"
    },
    articles: {
        title: "Gen Prose | Articles",
        description: "View articles related to and generated by Gen prose.",
        keywords: "genprose articles, genprose blogs, free audio to text converted, podcast to text blogs, about genprose, articles about youtube video to text generator"
    }
}